Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
scenario_analysis_usingET = ETAnalysis()
decision_ds, event_type = scenario_analysis_usingET.irrigation_delineation(ds_analysis_EO)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/xarray/core/dataset.py[0m in [0;36m?[0;34m(self, name)[0m
[1;32m   1512[0m             [0mvariable[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_variables[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m   1513[0m         [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1514[0;31m             [0m_[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0mvariable[0m [0;34m=[0m [0m_get_virtual_variable[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_variables[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0msizes[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1515[0m [0;34m[0m[0m

[0;31mKeyError[0m: 'ETa'

During handling of the above exception, another exception occurred:

[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/xarray/core/dataset.py[0m in [0;36m?[0;34m(self, key)[0m
[1;32m   1622[0m                 [0;32mif[0m [0misinstance[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0mtuple[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1623[0m                     [0mmessage[0m [0;34m+=[0m [0;34mf"\nHint: use a list to select multiple variables, for example `ds[{list(key)}]`"[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1624[0;31m                 [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0mmessage[0m[0;34m)[0m [0;32mfrom[0m [0me[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1625[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/xarray/core/dataset.py[0m in [0;36m?[0;34m(self, name)[0m
[1;32m   1512[0m             [0mvariable[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_variables[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m   1513[0m         [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1514[0;31m             [0m_[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0mvariable[0m [0;34m=[0m [0m_get_virtual_variable[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_variables[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0msizes[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1515[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/xarray/core/dataset.py[0m in [0;36m?[0;34m(variables, key, dim_sizes)[0m
[1;32m    219[0m     [0msplit_key[0m [0;34m=[0m [0mkey[0m[0;34m.[0m[0msplit[0m[0;34m([0m[0;34m"."[0m[0;34m,[0m [0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    220[0m     [0;32mif[0m [0mlen[0m[0;34m([0m[0msplit_key[0m[0;34m)[0m [0;34m!=[0m [0;36m2[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 221[0;31m         [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    222[0m [0;34m[0m[0m

[0;31mKeyError[0m: 'ETa'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_2116/2577214387.py[0m in [0;36m?[0;34m()[0m
[1;32m      1[0m [0mscenario_analysis_usingET[0m [0;34m=[0m [0mETAnalysis[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mdecision_ds[0m[0;34m,[0m [0mevent_type[0m [0;34m=[0m [0mscenario_analysis_usingET[0m[0;34m.[0m[0mirrigation_delineation[0m[0;34m([0m[0mds_analysis_EO[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/centum-0.1.5-py3.10.egg/centum/delineation.py[0m in [0;36m?[0;34m(self, decision_ds, threshold_local, threshold_regional, time_window)[0m
[1;32m    379[0m                                [0mtime_window[0m[0;34m=[0m[0;36m10[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    380[0m                                ):
[1;32m    381[0m [0;34m[0m[0m
[1;32m    382[0m         [0;31m# Compute local and regional ETa/ETp ratios[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 383[0;31m         [0mdecision_ds[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mcompute_ratio_ETap_local[0m[0;34m([0m[0mdecision_ds[0m[0;34m,[0m[0mtime_window[0m[0;34m=[0m[0mtime_window[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    384[0m         [0mdecision_ds[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mcompute_ratio_ETap_regional[0m[0;34m([0m[0mdecision_ds[0m[0;34m,[0m[0mtime_window[0m[0;34m=[0m[0mtime_window[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    385[0m [0;34m[0m[0m
[1;32m    386[0m         [0;31m# Apply local and regional threshold decision rules[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/centum-0.1.5-py3.10.egg/centum/delineation.py[0m in [0;36m?[0;34m(self, ds_analysis, ETa_name, ETp_name, time_window)[0m
[1;32m     54[0m         [0mxr[0m[0;34m.[0m[0mDataset[0m[0;34m[0m[0;34m[0m[0m
[1;32m     55[0m             [0mThe[0m [0mdataset[0m [0;32mwith[0m [0madded[0m [0mlocal[0m [0mETa[0m[0;34m/[0m[0mETp[0m [0mratio[0m [0;32mand[0m [0mtemporal[0m [0mdifferences[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m     56[0m         """
[1;32m     57[0m         [0;31m# Compute the local ratio of ETa/ETp[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 58[0;31m         [0mds_analysis[0m[0;34m[[0m[0;34m"ratio_ETap_local"[0m[0;34m][0m [0;34m=[0m [0mds_analysis[0m[0;34m[[0m[0mETa_name[0m[0;34m][0m [0;34m/[0m [0mds_analysis[0m[0;34m[[0m[0mETp_name[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     59[0m [0;34m[0m[0m
[1;32m     60[0m         [0;31m# Compute the absolute temporal difference of the local ratio[0m[0;34m[0m[0;34m[0m[0m
[1;32m     61[0m         ds_analysis["ratio_ETap_local_diff"] = abs(

[0;32m/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/xarray/core/dataset.py[0m in [0;36m?[0;34m(self, key)[0m
[1;32m   1620[0m [0;34m[0m[0m
[1;32m   1621[0m                 [0;31m# If someone attempts `ds['foo' , 'bar']` instead of `ds[['foo', 'bar']]`[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1622[0m                 [0;32mif[0m [0misinstance[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0mtuple[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1623[0m                     [0mmessage[0m [0;34m+=[0m [0;34mf"\nHint: use a list to select multiple variables, for example `ds[{list(key)}]`"[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1624[0;31m                 [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0mmessage[0m[0;34m)[0m [0;32mfrom[0m [0me[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1625[0m [0;34m[0m[0m
[1;32m   1626[0m         [0;32mif[0m [0mutils[0m[0;34m.[0m[0miterable_of_hashable[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1627[0m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_copy_listed[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: "No variable named 'ETa'. Did you mean one of ('ETp',)?"

