Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
GeoAnalysis = IrrigationDistrict(Majadas_CLC_shapefile)
gdf_CLC = GeoAnalysis.load_shapefile()
resolution = 10
bounds = gdf_CLC.total_bounds  # (minx, miny, maxx, maxy)
gdf_CLC['index'] = gdf_CLC['Code_18']
clc_rxr = GeoAnalysis.convert_to_rioxarray(gdf=gdf_CLC, 
                                            variable="index", 
                                            resolution=resolution, 
                                            bounds=bounds
                                            )
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[5], line 6[0m
[1;32m      4[0m bounds [38;5;241m=[39m gdf_CLC[38;5;241m.[39mtotal_bounds  [38;5;66;03m# (minx, miny, maxx, maxy)[39;00m
[1;32m      5[0m gdf_CLC[[38;5;124m'[39m[38;5;124mindex[39m[38;5;124m'[39m] [38;5;241m=[39m gdf_CLC[[38;5;124m'[39m[38;5;124mCode_18[39m[38;5;124m'[39m]
[0;32m----> 6[0m clc_rxr [38;5;241m=[39m [43mGeoAnalysis[49m[38;5;241;43m.[39;49m[43mconvert_to_rioxarray[49m(gdf[38;5;241m=[39mgdf_CLC, 
[1;32m      7[0m                                             variable[38;5;241m=[39m[38;5;124m"[39m[38;5;124mindex[39m[38;5;124m"[39m, 
[1;32m      8[0m                                             resolution[38;5;241m=[39mresolution, 
[1;32m      9[0m                                             bounds[38;5;241m=[39mbounds
[1;32m     10[0m                                             )

[0;31mAttributeError[0m: 'IrrigationDistrict' object has no attribute 'convert_to_rioxarray'

